// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoCaigo.Infrastructure.Persistencia;

#nullable disable

namespace NoCaigo.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(NoCaigoDbContext))]
    partial class NoCaigoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NoCaigo.Domain.Entidades.Analisis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Explicacion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("NivelRiesgo")
                        .HasColumnType("int");

                    b.Property<string>("TextoAnonimizado")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("TipoEstafaId")
                        .HasColumnType("int");

                    b.Property<bool>("UsoIA")
                        .HasColumnType("bit");

                    b.Property<string>("Veredicto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("TipoEstafaId");

                    b.ToTable("Analisis", (string)null);
                });

            modelBuilder.Entity("NoCaigo.Domain.Entidades.Senal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalisisId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AnalisisId");

                    b.ToTable("Senales", (string)null);
                });

            modelBuilder.Entity("NoCaigo.Domain.Entidades.TipoEstafa", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposEstafa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Falso banco"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Paquete retenido"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Falso familiar"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Premio falso"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Falsa oferta de trabajo"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Inversión falsa"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Otro"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Ninguno"
                        });
                });

            modelBuilder.Entity("NoCaigo.Domain.Entidades.Analisis", b =>
                {
                    b.HasOne("NoCaigo.Domain.Entidades.TipoEstafa", "TipoEstafa")
                        .WithMany()
                        .HasForeignKey("TipoEstafaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoEstafa");
                });

            modelBuilder.Entity("NoCaigo.Domain.Entidades.Senal", b =>
                {
                    b.HasOne("NoCaigo.Domain.Entidades.Analisis", null)
                        .WithMany("Senales")
                        .HasForeignKey("AnalisisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoCaigo.Domain.Entidades.Analisis", b =>
                {
                    b.Navigation("Senales");
                });
#pragma warning restore 612, 618
        }
    }
}
